### PR TITLE
fix source view

### PR DESCRIPTION
**Pull request by perissology**
get source view working again after recent changes

fix a few bugs regarding memRef

### CODE REVIEW

**Comment by tintinweb** [comment]
did I break something with #51?
I would also like to start some basic high-level unittesting. Any preferences for testdrivers?

**Comment by perissology** [comment]
I think it had to do with web3 update a while back.

**Comment by holiman** [comment]
This now has conflicts -- if this is still needed, could you please fix the conflicts @perissology  ?

**Comment by tintinweb** [comment]
rebased this PR and created a new branch as I am not allowed to push to @perissology master ;) --> #59

**Pull request closed without merging**
