### PR TITLE
Fixed Constantinople opcodes count

### PR DESCRIPTION
**Pull request by wtf**

### CODE REVIEW

**Comment by holiman** [comment]
Hey! Yes, that got borked and I didn't have time to commit the fix. However, I think you forgot to actually include the typo-fix? 
Also, you have changed it into being a list instead of a generator, which is less good from a a memory consumption perspective.

**Comment by wtf** [comment]
Oh yeah, the typo fix broke other things (basically, the evmlab package itself has the typo so it should be in another pull request)

I did change it from a generator to a list because it was being iterated twice. Let me refactor this.

**Comment by wtf** [comment]
Actually, I don't think there is any way around this.. Since `canonicalizer(output)` is a generator, it can only be used once. Either we can read store two copies of it in memory, i.e. `canon_steps` and `canon_trace`, or we can iterate through the file twice, which is worse.

**Comment by holiman** [comment]
Closing in favour of https://github.com/ethereum/evmlab/pull/85

**Pull request closed without merging**
